# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/singenmc_clock.xdc

# XDC: imports/sysgen/singenmc.xdc

# Block Designs: bd/singenmc_bd/singenmc_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singenmc_bd || ORIG_REF_NAME==singenmc_bd} -quiet] -quiet

# IP: bd/singenmc_bd/ip/singenmc_bd_singenmc_1_0/singenmc_bd_singenmc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singenmc_bd_singenmc_1_0 || ORIG_REF_NAME==singenmc_bd_singenmc_1_0} -quiet] -quiet

# XDC: /xilinxworks/sysgen/singen_panda/netlist/ip/singenmc/src/ip_catalog/singenmc.gen/sources_1/bd/singenmc_bd/singenmc_bd_ooc.xdc
