# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /xilinxworks/sysgen/singen_panda/netlist/ip/singenmc/src/ip_catalog/singenmc.srcs/sources_1/bd/singenmc_bd/ip/singenmc_bd_singenmc_1_0/singenmc_bd_singenmc_1_0.xci
# IP: The module: 'singenmc_bd_singenmc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /xilinxworks/sysgen/singen_panda/netlist/ip/singenmc/src/ip_catalog/singenmc.gen/sources_1/bd/singenmc_bd/ip/singenmc_bd_singenmc_1_0/singenmc_dds_compiler_v6_0_i0/singenmc_dds_compiler_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singenmc_dds_compiler_v6_0_i0 || ORIG_REF_NAME==singenmc_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/singen_panda/netlist/ip/singenmc/src/ip_catalog/singenmc.gen/sources_1/bd/singenmc_bd/ip/singenmc_bd_singenmc_1_0/singenmc_mult_gen_v12_0_i0/singenmc_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singenmc_mult_gen_v12_0_i0 || ORIG_REF_NAME==singenmc_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: /xilinxworks/sysgen/singen_panda/netlist/ip/singenmc/src/ip_catalog/singenmc.gen/sources_1/bd/singenmc_bd/ip/singenmc_bd_singenmc_1_0/constrs/singenmc.xdc
# XDC: The top module name and the constraint reference have the same name: 'singenmc_bd_singenmc_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /xilinxworks/sysgen/singen_panda/netlist/ip/singenmc/src/ip_catalog/singenmc.srcs/sources_1/bd/singenmc_bd/ip/singenmc_bd_singenmc_1_0/singenmc_bd_singenmc_1_0.xci
# IP: The module: 'singenmc_bd_singenmc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /xilinxworks/sysgen/singen_panda/netlist/ip/singenmc/src/ip_catalog/singenmc.gen/sources_1/bd/singenmc_bd/ip/singenmc_bd_singenmc_1_0/singenmc_dds_compiler_v6_0_i0/singenmc_dds_compiler_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singenmc_dds_compiler_v6_0_i0 || ORIG_REF_NAME==singenmc_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/singen_panda/netlist/ip/singenmc/src/ip_catalog/singenmc.gen/sources_1/bd/singenmc_bd/ip/singenmc_bd_singenmc_1_0/singenmc_mult_gen_v12_0_i0/singenmc_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singenmc_mult_gen_v12_0_i0 || ORIG_REF_NAME==singenmc_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: /xilinxworks/sysgen/singen_panda/netlist/ip/singenmc/src/ip_catalog/singenmc.gen/sources_1/bd/singenmc_bd/ip/singenmc_bd_singenmc_1_0/constrs/singenmc.xdc
# XDC: The top module name and the constraint reference have the same name: 'singenmc_bd_singenmc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
